### ISSUE TITLE
Sorry can't get this working!

### ISSUE THREAD

**Issue by andywhitfield568** [flautrup/QlikSenseWebsocketConnectivityTester#7]
Hi,
I have followed:
•	Download the zip file from github
•	Unzip onto the Qlik Sense Server
•	In the QMC create a Content Library
•	Upload QlikSenseWebsocketTest.hml file to content library
•	Browse content library content and use URL path to access the file in the browser

But don't understand how you do this section

•	Browse content library content and use URL path to access the file in the browser

![image](https://user-images.githubusercontent.com/18164645/41099555-ced33d98-6a56-11e8-8a97-5e3ba5dabc85.png)

Thanks in advance

Andy

**Comment by flautrup** [comment]
Just copy the content of the URL path field and add that in the browser
after your server name like this
https://[Server
name]/content/Connectivity%20Tester/QlikSenseWebsocketTest.html

//Fredrik

2018-06-07 14:29 GMT+02:00 andywhitfield568 <notifications@github.com>:

**Comment by andywhitfield568** [comment]
Hi Fredrik,

Thanks for the heads up, got it working now 😉

Best regards,

Andy

Andy Whitfield
Support Analyst – Managed Services

T: 0161 232 7100 |E: bisupport@caci.co.uk |W: www.caci.co.uk<http://www.caci.co.uk/> | F: 0161 226 2200
Synergy House, Manchester Science Park, Manchester, M15 6SY
P  Please consider the environment before printing this e-mail
